config/routes.rb
Rails.application.routes.draw do
    root 'webhooks#index'

    resources :webhooks do
    end

    post 'open' => 'webhooks#webhook'
    post 'click' => 'webhooks#webhook'
end

app/models/webhook.rb
class Webhook < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  before_action :set_webhook, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, only: [:webhook]

  def webhook
    @webhook = Webhook.new
    @webhook.event = params[:event]
    @webhook.recipient = params[:recipient]
    @webhook.domain = params[:domain]
    @webhook.ip = params[:ip]
    @webhook.country = params[:country]
    @webhook.region = params[:region]
    @webhook.city = params[:city]
    @webhook.save
    head :no_content
  end

  # GET /webhooks
  # GET /webhooks.json
  def index
    @webhooks = Webhook.all
  end

  # GET /webhooks/1
  # GET /webhooks/1.json
  def show
  end

  # GET /webhooks/new
  def new
    @webhook = Webhook.new
  end

  # GET /webhooks/1/edit
  def edit
  end

  # POST /webhooks
  # POST /webhooks.json
  def create
    @webhook = Webhook.new(webhook_params)

    respond_to do |format|
      if @webhook.save
        format.html { redirect_to @webhook, notice: 'Webhook was successfully created.' }
        format.json { render :show, status: :created, location: @webhook }
      else
        format.html { render :new }
        format.json { render json: @webhook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /webhooks/1
  # PATCH/PUT /webhooks/1.json
  def update
    respond_to do |format|
      if @webhook.update(webhook_params)
        format.html { redirect_to @webhook, notice: 'Webhook was successfully updated.' }
        format.json { render :show, status: :ok, location: @webhook }
      else
        format.html { render :edit }
        format.json { render json: @webhook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webhooks/1
  # DELETE /webhooks/1.json
  def destroy
    @webhook.destroy
    respond_to do |format|
      format.html { redirect_to webhooks_url, notice: 'Webhook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_webhook
      @webhook = Webhook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def webhook_params
      params.fetch(:webhook, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webhooks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/webhooks/_form.html.erb
<%= form_for(@webhook) do |f| %>
  <% if @webhook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@webhook.errors.count, "error") %> prohibited this webhook from being saved:</h2>

      <ul>
      <% @webhook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/webhooks/edit.html.erb
<h1>Editing Webhook</h1>

<%= render 'form' %>

<%= link_to 'Show', @webhook %> |
<%= link_to 'Back', webhooks_path %>

app/views/webhooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Webhooks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @webhooks.each do |webhook| %>
      <tr>
        <td><%= link_to 'Show', webhook %></td>
        <td><%= link_to 'Edit', edit_webhook_path(webhook) %></td>
        <td><%= link_to 'Destroy', webhook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Webhook', new_webhook_path %>

app/views/webhooks/new.html.erb
<h1>New Webhook</h1>

<%= render 'form' %>

<%= link_to 'Back', webhooks_path %>

app/views/webhooks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_webhook_path(@webhook) %> |
<%= link_to 'Back', webhooks_path %>